syntax on

set ruler

set nobackup

set ignorecase
set smartcase
set hlsearch
set incsearch

set autoindent
set smarttab
if has("autocmd")
  filetype on
  filetype indent on
  filetype plugin on
endif

if has("multi_byte")
  set encoding=utf-8
  set list listchars=tab:»·,trail:·
else
  set list listchars=tab:>-,trail:.
endif

set mouse=

set nocompatible              " be iMproved, required
filetype off                  " required
